baseURL = "https://example.com"

# This is a "one posts"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The browser tab name
title = "Event Storming"

# In order to add version information in the posts's footer set to true.
# enableGitInfo = true

# Theme-specific variables `.Site.Params.myParamName`
[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/cover-image.png"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Event Storming"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Szkolenia z Event Stormingu"

    # A "copyright"-line to be added at the bottom of the posts.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-posts.
    copyright = "© <a href="https://matee.net/?utm_source=eventstorming.training&utm_medium=www&utm_campaign=www&utm_content=footer">Mateusz Pawlik</a>"

    # This theme will, by default, inject a design-by-line at the bottom of the posts.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = false

    # The sections of the home posts alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false
    
    [params.meta]
        keywords = "event, storming, eventstorming, trening, warsztat, szkolenie, coach, training, workshop, ddd, cqrs, proces biznesowy, architektura"
